update workflow
Signed-off-by: bupd <bupdprasanth@gmail.com>

diff --git a/.github/workflows/default.yaml b/.github/workflows/default.yaml
--- a/.github/workflows/default.yaml
+++ b/.github/workflows/default.yaml
@@ -22,7 +22,7 @@ jobs:
       - name: Dagger Version
         uses: sagikazarmark/dagger-version-action@v0.0.1
 
-      - name: Generate Documentation
+      - name: Generate Document
         uses: dagger/dagger-for-github@v7
         with:
           version: ${{ steps.dagger_version.outputs.version }}
@@ -31,8 +31,17 @@ jobs:
 
       - name: Check for changes
         run: |
-          # Check if any files were changed by document
-          git diff --exit-code
+          # Check if any untracked files exist
+          untracked_files=$(git ls-files --others --exclude-standard)
+
+          # If there are untracked files, fail the workflow
+          if [ -n "$untracked_files" ]; then
+            echo "Untracked files found:"
+            echo "$untracked_files"
+            exit 1  # This will fail the workflow
+          else
+            echo "No untracked files found."
+          fi
         continue-on-error: false
 
       - name: Run Dagger golangci-lint
